### ISSUE TITLE
기능 명세서 작성

### ISSUE THREAD

**Issue by devejs** [ios-study-boost/COVID-19-iOS#1]
작성한 기능 명세서 업로드

**Comment by IMCHO** [comment]
<img width="1299" alt="스크린샷 2020-10-13 오전 11 47 24" src="https://user-images.githubusercontent.com/34809813/95809508-f3439b80-0d49-11eb-9781-1b8bec4bc9f6.png">

**Comment by devejs** [comment]
![기능명세서-초안](https://user-images.githubusercontent.com/48985445/95807296-c476f680-0d44-11eb-921d-d94332c2f9f7.png)
