### ISSUE TITLE
화면 설계서 작성

### ISSUE THREAD

**Issue by devejs** [ios-study-boost/COVID-19-iOS#2]
작성한 화면 설계서 업로드  

이름|담당 파트
---|---
조인택| 메인 화면
신은지| 지역별 뷰, 해외국가 뷰

**Comment by devejs** [comment]
![Uploading IMG_2720.jpg…]()

**Comment by devejs** [comment]
![IMG_2720](https://user-images.githubusercontent.com/48985445/96117804-9c92b900-0f25-11eb-93b8-4c64df13d1aa.jpg)

**Comment by IMCHO** [comment]
<img width="1340" alt="스크린샷 2020-10-15 오후 9 08 10" src="https://user-images.githubusercontent.com/34809813/96121397-fea1ed00-0f2a-11eb-9539-14f080dd66e4.png">
