### ISSUE TITLE
커밋,  코딩 Convention 정하기

### ISSUE THREAD

**Issue by IMCHO** [ios-study-boost/COVID-19-iOS#9]

**Comment by IMCHO** [comment]
```
// 형식
type: subject

// 예시
feat: Summarize changes in around 50 characters or less
```

### type
- feat : 새로운 기능 추가
- fix : 버그 수정
- docs : 문서 수정
- style : 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
- refactor : 코드 리팩토링

[이 곳](https://doublesprogramming.tistory.com/256)을 참고했습니다.

**Comment by IMCHO** [comment]
이정도면 충분할까요?
혹시 뒤에 subject는 영어로 할까요 한글로 할까요?

**Comment by devejs** [comment]
영어가 나을 것 같아요! 영어로 표현이 정 안되는 것만 제외하면..?

**Comment by IMCHO** [comment]
네네 영어로 하시죠~!
